export const symbols = {
  "code": 1,
  "data": [
      {
          "contract_size": 1000.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -2.27,
          "swap_short": 0.45,
          "symbol": "UKOIL",
          "type": 2,
          "type_name": "CFD"
      },
      {
          "contract_size": 1000.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -1.55,
          "swap_short": 0.17,
          "symbol": "USOIL",
          "type": 2,
          "type_name": "CFD"
      },
      {
          "contract_size": 10000.0,
          "currency": "USD",
          "digits": 4,
          "margin_currency": "USD",
          "margin_mode": 4,
          "point": 0.0001,
          "swap_long": -40.0,
          "swap_short": -10.0,
          "symbol": "XNGUSD",
          "type": 2,
          "type_name": "CFD"
      },
      {
          "contract_size": 300.0,
          "currency": "CNY",
          "digits": 2,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -3.0,
          "swap_short": -2.0,
          "symbol": "CHINA300",
          "type": 2,
          "type_name": "CFD"
      },
      {
          "contract_size": 10.0,
          "currency": "USD",
          "digits": 1,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "ChinaA50",
          "type": 2,
          "type_name": "CFD"
      },
      {
          "contract_size": 5.0,
          "currency": "USD",
          "digits": 1,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "DOW",
          "type": 2,
          "type_name": "CFD"
      },
      {
          "contract_size": 50.0,
          "currency": "HKD",
          "digits": 0,
          "margin_currency": "HKD",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "HSI",
          "type": 2,
          "type_name": "CFD"
      },
      {
          "contract_size": 1000.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "USDX",
          "type": 2,
          "type_name": "CFD"
      },
      {
          "contract_size": 1.0,
          "currency": "AUD",
          "digits": 1,
          "margin_currency": "AUD",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "AU200",
          "type": 1,
          "type_name": "Indexes"
      },
      {
          "contract_size": 1.0,
          "currency": "EUR",
          "digits": 1,
          "margin_currency": "EUR",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": -60.2,
          "swap_short": -70.0,
          "symbol": "EU50",
          "type": 1,
          "type_name": "Indexes"
      },
      {
          "contract_size": 1.0,
          "currency": "EUR",
          "digits": 1,
          "margin_currency": "EUR",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "FR40",
          "type": 1,
          "type_name": "Indexes"
      },
      {
          "contract_size": 1.0,
          "currency": "EUR",
          "digits": 1,
          "margin_currency": "EUR",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": -16.51,
          "swap_short": -20.41,
          "symbol": "DE30",
          "type": 1,
          "type_name": "Indexes"
      },
      {
          "contract_size": 1.0,
          "currency": "HKD",
          "digits": 1,
          "margin_currency": "HKD",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": -52.61,
          "swap_short": -46.68,
          "symbol": "HK50",
          "type": 1,
          "type_name": "Indexes"
      },
      {
          "contract_size": 10.0,
          "currency": "JPY",
          "digits": 0,
          "margin_currency": "JPY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": -53.4,
          "swap_short": -54.7,
          "symbol": "JP225",
          "type": 1,
          "type_name": "Indexes"
      },
      {
          "contract_size": 1.0,
          "currency": "EUR",
          "digits": 1,
          "margin_currency": "EUR",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "E35",
          "type": 1,
          "type_name": "Indexes"
      },
      {
          "contract_size": 1.0,
          "currency": "GBP",
          "digits": 1,
          "margin_currency": "GBP",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": -88.4,
          "swap_short": -86.8,
          "symbol": "UK100",
          "type": 1,
          "type_name": "Indexes"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 1,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "US500",
          "type": 1,
          "type_name": "Indexes"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 1,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "UT100",
          "type": 1,
          "type_name": "Indexes"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 1,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": -38.25,
          "swap_short": -35.95,
          "symbol": "US30",
          "type": 1,
          "type_name": "Indexes"
      },
      {
          "contract_size": 5.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "不锈钢主连",
          "type": 5,
          "type_name": "SHFE"
      },
      {
          "contract_size": 5.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "沪铝主连",
          "type": 5,
          "type_name": "SHFE"
      },
      {
          "contract_size": 1.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "沪镍主连",
          "type": 5,
          "type_name": "SHFE"
      },
      {
          "contract_size": 5.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "沪铅主连",
          "type": 5,
          "type_name": "SHFE"
      },
      {
          "contract_size": 5.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "沪铜主连",
          "type": 5,
          "type_name": "SHFE"
      },
      {
          "contract_size": 1.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "沪锡主连",
          "type": 5,
          "type_name": "SHFE"
      },
      {
          "contract_size": 5.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "沪锌主连",
          "type": 5,
          "type_name": "SHFE"
      },
      {
          "contract_size": 15.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "沪银主连",
          "type": 5,
          "type_name": "SHFE"
      },
      {
          "contract_size": 1000.0,
          "currency": "CNY",
          "digits": 2,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "黄金主连",
          "type": 5,
          "type_name": "SHFE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "沥青主连",
          "type": 5,
          "type_name": "SHFE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "螺纹主连",
          "type": 5,
          "type_name": "SHFE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "燃油主连",
          "type": 5,
          "type_name": "SHFE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "热卷主连",
          "type": 5,
          "type_name": "SHFE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "橡胶主连",
          "type": 5,
          "type_name": "SHFE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "纸浆主连",
          "type": 5,
          "type_name": "SHFE"
      },
      {
          "contract_size": 300.0,
          "currency": "CNY",
          "digits": 1,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "沪深主连",
          "type": 6,
          "type_name": "CFFEX"
      },
      {
          "contract_size": 300.0,
          "currency": "CNY",
          "digits": 1,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "上证主连",
          "type": 6,
          "type_name": "CFFEX"
      },
      {
          "contract_size": 10000.0,
          "currency": "CNY",
          "digits": 3,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 0.001,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "债十主连",
          "type": 6,
          "type_name": "CFFEX"
      },
      {
          "contract_size": 10000.0,
          "currency": "CNY",
          "digits": 3,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 0.001,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "债二主连",
          "type": 6,
          "type_name": "CFFEX"
      },
      {
          "contract_size": 10000.0,
          "currency": "CNY",
          "digits": 3,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 0.001,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "债五主连",
          "type": 6,
          "type_name": "CFFEX"
      },
      {
          "contract_size": 200.0,
          "currency": "CNY",
          "digits": 1,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "中证主连",
          "type": 6,
          "type_name": "CFFEX"
      },
      {
          "contract_size": 5.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "PVC主连",
          "type": 7,
          "type_name": "DCE"
      },
      {
          "contract_size": 5.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "苯乙烯主连",
          "type": 7,
          "type_name": "DCE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "淀粉主连",
          "type": 7,
          "type_name": "DCE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "豆粕主连",
          "type": 7,
          "type_name": "DCE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "豆一主连",
          "type": 7,
          "type_name": "DCE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "豆油主连",
          "type": 7,
          "type_name": "DCE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "鸡蛋主连",
          "type": 7,
          "type_name": "DCE"
      },
      {
          "contract_size": 60.0,
          "currency": "CNY",
          "digits": 1,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "焦煤主连",
          "type": 7,
          "type_name": "DCE"
      },
      {
          "contract_size": 100.0,
          "currency": "CNY",
          "digits": 1,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "焦炭主连",
          "type": 7,
          "type_name": "DCE"
      },
      {
          "contract_size": 5.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "聚丙烯主连",
          "type": 7,
          "type_name": "DCE"
      },
      {
          "contract_size": 5.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "塑料主连",
          "type": 7,
          "type_name": "DCE"
      },
      {
          "contract_size": 100.0,
          "currency": "CNY",
          "digits": 1,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "铁矿主连",
          "type": 7,
          "type_name": "DCE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "乙二醇主连",
          "type": 7,
          "type_name": "DCE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "玉米主连",
          "type": 7,
          "type_name": "DCE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "棕榈主连",
          "type": 7,
          "type_name": "DCE"
      },
      {
          "contract_size": 5.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "PTA主连",
          "type": 8,
          "type_name": "CZCE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "白糖主连",
          "type": 8,
          "type_name": "CZCE"
      },
      {
          "contract_size": 20.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "玻璃主连",
          "type": 8,
          "type_name": "CZCE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "菜粕主连",
          "type": 8,
          "type_name": "CZCE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "菜油主连",
          "type": 8,
          "type_name": "CZCE"
      },
      {
          "contract_size": 5.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "红枣主连",
          "type": 8,
          "type_name": "CZCE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "甲醇主连",
          "type": 8,
          "type_name": "CZCE"
      },
      {
          "contract_size": 5.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "锰硅主连",
          "type": 8,
          "type_name": "CZCE"
      },
      {
          "contract_size": 5.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "棉花主连",
          "type": 8,
          "type_name": "CZCE"
      },
      {
          "contract_size": 5.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "棉纱主连",
          "type": 8,
          "type_name": "CZCE"
      },
      {
          "contract_size": 20.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "尿素主连",
          "type": 8,
          "type_name": "CZCE"
      },
      {
          "contract_size": 100.0,
          "currency": "CNY",
          "digits": 1,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "郑煤主连",
          "type": 8,
          "type_name": "CZCE"
      },
      {
          "contract_size": 20.0,
          "currency": "CNY",
          "digits": 1,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 0.1,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "纯碱主连",
          "type": 8,
          "type_name": "CZCE"
      },
      {
          "contract_size": 10.0,
          "currency": "CNY",
          "digits": 0,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 1.0,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "20号胶主连",
          "type": 9,
          "type_name": "INE"
      },
      {
          "contract_size": 1000.0,
          "currency": "CNY",
          "digits": 2,
          "margin_currency": "CNY",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": 0.0,
          "swap_short": 0.0,
          "symbol": "原油主连",
          "type": 9,
          "type_name": "INE"
      },
      {
          "contract_size": 100000.0,
          "currency": "AUD",
          "digits": 5,
          "margin_currency": "AUD",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -3.92,
          "swap_short": -3.99,
          "symbol": "AUDUSD",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "GBP",
          "digits": 5,
          "margin_currency": "GBP",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -5.54,
          "swap_short": -4.82,
          "symbol": "GBPUSD",
          "type": 21,
          "type_name": "FX.cvrt"
      },
      {
          "contract_size": 100000.0,
          "currency": "EUR",
          "digits": 5,
          "margin_currency": "EUR",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -5.6,
          "swap_short": -1.04,
          "symbol": "EURUSD",
          "type": 21,
          "type_name": "FX.cvrt"
      },
      {
          "contract_size": 100000.0,
          "currency": "NZD",
          "digits": 5,
          "margin_currency": "NZD",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -3.37,
          "swap_short": -2.7,
          "symbol": "NZDUSD",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "USD",
          "digits": 5,
          "margin_currency": "USD",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -4.33,
          "swap_short": -4.56,
          "symbol": "USDCAD",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "USD",
          "digits": 5,
          "margin_currency": "USD",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -0.63,
          "swap_short": -5.45,
          "symbol": "USDCHF",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "USD",
          "digits": 3,
          "margin_currency": "USD",
          "margin_mode": 0,
          "point": 0.001,
          "swap_long": -4.16,
          "swap_short": -5.97,
          "symbol": "USDJPY",
          "type": 21,
          "type_name": "FX.cvrt"
      },
      {
          "contract_size": 100000.0,
          "currency": "AUD",
          "digits": 5,
          "margin_currency": "AUD",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -3.23,
          "swap_short": -3.57,
          "symbol": "AUDCAD",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "AUD",
          "digits": 5,
          "margin_currency": "AUD",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -0.74,
          "swap_short": -4.24,
          "symbol": "AUDCHF",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "AUD",
          "digits": 3,
          "margin_currency": "AUD",
          "margin_mode": 0,
          "point": 0.001,
          "swap_long": -2.91,
          "swap_short": -4.31,
          "symbol": "AUDJPY",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "AUD",
          "digits": 5,
          "margin_currency": "AUD",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -3.59,
          "swap_short": -4.84,
          "symbol": "AUDNZD",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "CAD",
          "digits": 5,
          "margin_currency": "CAD",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -0.87,
          "swap_short": -4.27,
          "symbol": "CADCHF",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "CAD",
          "digits": 3,
          "margin_currency": "CAD",
          "margin_mode": 0,
          "point": 0.001,
          "swap_long": -3.1,
          "swap_short": -4.3,
          "symbol": "CADJPY",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "CHF",
          "digits": 3,
          "margin_currency": "CHF",
          "margin_mode": 0,
          "point": 0.001,
          "swap_long": -6.29,
          "swap_short": -2.21,
          "symbol": "CHFJPY",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "EUR",
          "digits": 5,
          "margin_currency": "EUR",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -8.42,
          "swap_short": -1.85,
          "symbol": "EURAUD",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "EUR",
          "digits": 5,
          "margin_currency": "EUR",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -7.29,
          "swap_short": -1.65,
          "symbol": "EURCAD",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "EUR",
          "digits": 5,
          "margin_currency": "EUR",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -2.59,
          "swap_short": -4.03,
          "symbol": "EURCHF",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "EUR",
          "digits": 5,
          "margin_currency": "EUR",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -5.45,
          "swap_short": -2.45,
          "symbol": "EURGBP",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "EUR",
          "digits": 3,
          "margin_currency": "EUR",
          "margin_mode": 0,
          "point": 0.001,
          "swap_long": -5.87,
          "swap_short": -3.19,
          "symbol": "EURJPY",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "EUR",
          "digits": 5,
          "margin_currency": "EUR",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -8.0,
          "swap_short": -2.91,
          "symbol": "EURNZD",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "GBP",
          "digits": 5,
          "margin_currency": "GBP",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -8.35,
          "swap_short": -7.11,
          "symbol": "GBPAUD",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "GBP",
          "digits": 5,
          "margin_currency": "GBP",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -7.18,
          "swap_short": -6.63,
          "symbol": "GBPCAD",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "GBP",
          "digits": 5,
          "margin_currency": "GBP",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -2.4,
          "swap_short": -7.93,
          "symbol": "GBPCHF",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "GBP",
          "digits": 3,
          "margin_currency": "GBP",
          "margin_mode": 0,
          "point": 0.001,
          "swap_long": -5.81,
          "swap_short": -7.38,
          "symbol": "GBPJPY",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "GBP",
          "digits": 5,
          "margin_currency": "GBP",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -7.9,
          "swap_short": -8.71,
          "symbol": "GBPNZD",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "NZD",
          "digits": 5,
          "margin_currency": "NZD",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -3.59,
          "swap_short": -2.86,
          "symbol": "NZDCAD",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "NZD",
          "digits": 5,
          "margin_currency": "NZD",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -1.12,
          "swap_short": -3.6,
          "symbol": "NZDCHF",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "NZD",
          "digits": 3,
          "margin_currency": "NZD",
          "margin_mode": 0,
          "point": 0.001,
          "swap_long": -3.22,
          "swap_short": -3.7,
          "symbol": "NZDJPY",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -7.08,
          "swap_short": -3.88,
          "symbol": "XAUUSD",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 5000.0,
          "currency": "USD",
          "digits": 3,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.001,
          "swap_long": -1.95,
          "swap_short": -1.38,
          "symbol": "XAGUSD",
          "type": 20,
          "type_name": "FX.comn"
      },
      {
          "contract_size": 100000.0,
          "currency": "USD",
          "digits": 5,
          "margin_currency": "USD",
          "margin_mode": 0,
          "point": 1e-05,
          "swap_long": -115.0,
          "swap_short": -21.0,
          "symbol": "USDHKD",
          "type": 21,
          "type_name": "FX.cvrt"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Alibaba",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Alphabet",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Amazon",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Apple",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Berkshire.H",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Boeing",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Citigroup",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Coca-Cola",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Disney",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Exxon",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Facebook",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Goldmans",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "JPMorgan",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Microsoft",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "NVIDIA",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Netflix",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Starbucks",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Tesla",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Twitter",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "UBER",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "Walmart",
          "type": 22,
          "type_name": "Equities"
      },
      {
          "contract_size": 1.0,
          "currency": "USD",
          "digits": 2,
          "margin_currency": "USD",
          "margin_mode": 1,
          "point": 0.01,
          "swap_long": -4.6,
          "swap_short": -0.4,
          "symbol": "eBay",
          "type": 22,
          "type_name": "Equities"
      }
  ],
  "msg": ""
}

export const plist = [
  {
    "close_price": 104.917,
    "close_time": "2020-11-10 10:03:27",
    "cmd": 0,
    "comment": "",
    "commission": 0.0,
    "login": 10569,
    "open_price": 104.714,
    "open_time": "2020-11-02 07:59:38",
    "profit": 1.9300000000000002,
    "sl": 0.0,
    "storage": -0.32,
    "symbol": "USDJPY",
    "ticket": 1194942,
    "tp": 0.0,
    "volume": 0.08
  },
  {
      "close_price": 1.18306,
      "close_time": "2020-11-10 10:03:27",
      "cmd": 1,
      "comment": "from #1213414",
      "commission": 0.0,
      "login": 10569,
      "open_price": 1.18892,
      "open_time": "2020-11-09 04:11:57",
      "profit": 5.86,
      "sl": 1.2,
      "storage": -0.01,
      "symbol": "EURUSD",
      "ticket": 1213582,
      "tp": 0.0,
      "volume": 0.02
  },
  {
      "close_price": 1.18306,
      "close_time": "2020-11-10 10:03:27",
      "cmd": 1,
      "comment": "",
      "commission": 0.0,
      "login": 10569,
      "open_price": 1.18893,
      "open_time": "2020-11-09 04:11:36",
      "profit": 11.74,
      "sl": 0.0,
      "storage": -0.02,
      "symbol": "EURUSD",
      "ticket": 1213408,
      "tp": 0.0,
      "volume": 0.02
  }
]
export const olist = [
  {
    "close_price": 104.917,
    "close_time": "2020-11-10 10:03:27",
    "cmd": 0,
    "comment": "",
    "commission": 0.0,
    "login": 10569,
    "open_price": 104.714,
    "open_time": "2020-11-02 07:59:38",
    "profit": 1.9300000000000002,
    "sl": 0.0,
    "storage": -0.32,
    "symbol": "USDJPY",
    "ticket": 1194942,
    "tp": 0.0,
    "volume": 0.01
  }
]